export const language = state => state.language
export const device = state => state.device
export const sidebar = state => state.sidebar
export const name = state => state.user.name
export const token = state => state.user.token
export const roles = state => state.user.roles
export const addRouters = state => state.user.addRouters
export const routers = state => state.user.routers
export const pageOpenedList = state => state.tabs.pageOpenedList
export const pageCachedList = state => state.tabs.pageCachedList
export const currentPage = state => state.tabs.currentPage
